# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170825_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=50)),
                ('Block', models.CharField(max_length=50)),
                ('Panchayat', models.CharField(max_length=50)),
                ('Village', models.CharField(max_length=50)),
                ('Habitation', models.CharField(max_length=50)),
                ('Parameter', models.CharField(choices=[('iron', 'IRON'), ('nitrate', 'NITRATE'), ('salinity', 'SALINITY'), ('fluoride', 'FLUORIDE'), ('arsenic', 'ARSENIC')], default='iron', max_length=10)),
                ('Permissible_limit', models.DecimalField(decimal_places=5, max_digits=6)),
                ('Actual_level', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='userss',
            name='Username',
        ),
        migrations.DeleteModel(
            name='Userss',
        ),
    ]
